tasks:
  build-deps:
    runner: razorci/openjdk:11-buster
    steps:
    - checkout
    
    - run: mvn -B clean install test
    - reports/junit: 
      - target/surefire-reports/TEST-*.xml
    - commands:
      - |
        curl -Os https://uploader.codecov.io/latest/linux/codecov 
        chmod +x codecov 
        ./codecov -t ${CODECOV_TOKEN}
        codecov/upload
       
